# Generated by Django 5.1.1 on 2024-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('trans_type', models.CharField(blank=True, choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=100, null=True)),
            ],
        ),
    ]
